// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: xmaspi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mode int32

const (
	Mode_MODE_INACTIVE  Mode = 0
	Mode_MODE_STATIC    Mode = 1
	Mode_MODE_ANIMATION Mode = 2
	Mode_MODE_MANUAL    Mode = 3
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_INACTIVE",
		1: "MODE_STATIC",
		2: "MODE_ANIMATION",
		3: "MODE_MANUAL",
	}
	Mode_value = map[string]int32{
		"MODE_INACTIVE":  0,
		"MODE_STATIC":    1,
		"MODE_ANIMATION": 2,
		"MODE_MANUAL":    3,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_xmaspi_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_xmaspi_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_xmaspi_proto_rawDescGZIP(), []int{0}
}

type ModeChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=Mode" json:"mode,omitempty"`
}

func (x *ModeChangeRequest) Reset() {
	*x = ModeChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xmaspi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModeChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeChangeRequest) ProtoMessage() {}

func (x *ModeChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xmaspi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeChangeRequest.ProtoReflect.Descriptor instead.
func (*ModeChangeRequest) Descriptor() ([]byte, []int) {
	return file_xmaspi_proto_rawDescGZIP(), []int{0}
}

func (x *ModeChangeRequest) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_INACTIVE
}

type ModeChangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModeChangeResponse) Reset() {
	*x = ModeChangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xmaspi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModeChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeChangeResponse) ProtoMessage() {}

func (x *ModeChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xmaspi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeChangeResponse.ProtoReflect.Descriptor instead.
func (*ModeChangeResponse) Descriptor() ([]byte, []int) {
	return file_xmaspi_proto_rawDescGZIP(), []int{1}
}

type SetLedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Led   int32  `protobuf:"varint,1,opt,name=led,proto3" json:"led,omitempty"`
	Color uint32 `protobuf:"varint,2,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *SetLedRequest) Reset() {
	*x = SetLedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xmaspi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLedRequest) ProtoMessage() {}

func (x *SetLedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xmaspi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLedRequest.ProtoReflect.Descriptor instead.
func (*SetLedRequest) Descriptor() ([]byte, []int) {
	return file_xmaspi_proto_rawDescGZIP(), []int{2}
}

func (x *SetLedRequest) GetLed() int32 {
	if x != nil {
		return x.Led
	}
	return 0
}

func (x *SetLedRequest) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

type SetLedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLedResponse) Reset() {
	*x = SetLedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xmaspi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLedResponse) ProtoMessage() {}

func (x *SetLedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xmaspi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLedResponse.ProtoReflect.Descriptor instead.
func (*SetLedResponse) Descriptor() ([]byte, []int) {
	return file_xmaspi_proto_rawDescGZIP(), []int{3}
}

type SetAnimationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SetAnimationRequest) Reset() {
	*x = SetAnimationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xmaspi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAnimationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAnimationRequest) ProtoMessage() {}

func (x *SetAnimationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xmaspi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAnimationRequest.ProtoReflect.Descriptor instead.
func (*SetAnimationRequest) Descriptor() ([]byte, []int) {
	return file_xmaspi_proto_rawDescGZIP(), []int{4}
}

func (x *SetAnimationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetAnimationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetAnimationResponse) Reset() {
	*x = SetAnimationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xmaspi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAnimationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAnimationResponse) ProtoMessage() {}

func (x *SetAnimationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xmaspi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAnimationResponse.ProtoReflect.Descriptor instead.
func (*SetAnimationResponse) Descriptor() ([]byte, []int) {
	return file_xmaspi_proto_rawDescGZIP(), []int{5}
}

var File_xmaspi_proto protoreflect.FileDescriptor

var file_xmaspi_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x78, 0x6d, 0x61, 0x73, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e,
	0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x05, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x14,
	0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x6c, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x10, 0x0a,
	0x0e, 0x53, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x29, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x65,
	0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2a, 0x4f, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x4f,
	0x44, 0x45, 0x5f, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x49, 0x43, 0x10, 0x01, 0x12, 0x12,
	0x0a, 0x0e, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x41, 0x4e, 0x49, 0x4d, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x4d, 0x41, 0x4e, 0x55, 0x41,
	0x4c, 0x10, 0x03, 0x32, 0xa7, 0x01, 0x0a, 0x06, 0x58, 0x6d, 0x61, 0x73, 0x50, 0x49, 0x12, 0x35,
	0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x12,
	0x0e, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0f, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3b, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x6c, 0x64, 0x6f,
	0x72, 0x61, 0x6e, 0x44, 0x65, 0x76, 0x2f, 0x78, 0x6d, 0x61, 0x73, 0x70, 0x69, 0x2f, 0x76, 0x32,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xmaspi_proto_rawDescOnce sync.Once
	file_xmaspi_proto_rawDescData = file_xmaspi_proto_rawDesc
)

func file_xmaspi_proto_rawDescGZIP() []byte {
	file_xmaspi_proto_rawDescOnce.Do(func() {
		file_xmaspi_proto_rawDescData = protoimpl.X.CompressGZIP(file_xmaspi_proto_rawDescData)
	})
	return file_xmaspi_proto_rawDescData
}

var file_xmaspi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xmaspi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_xmaspi_proto_goTypes = []interface{}{
	(Mode)(0),                    // 0: Mode
	(*ModeChangeRequest)(nil),    // 1: ModeChangeRequest
	(*ModeChangeResponse)(nil),   // 2: ModeChangeResponse
	(*SetLedRequest)(nil),        // 3: SetLedRequest
	(*SetLedResponse)(nil),       // 4: SetLedResponse
	(*SetAnimationRequest)(nil),  // 5: SetAnimationRequest
	(*SetAnimationResponse)(nil), // 6: SetAnimationResponse
}
var file_xmaspi_proto_depIdxs = []int32{
	0, // 0: ModeChangeRequest.mode:type_name -> Mode
	1, // 1: XmasPI.ChangeMode:input_type -> ModeChangeRequest
	3, // 2: XmasPI.SetLed:input_type -> SetLedRequest
	5, // 3: XmasPI.SetAnimation:input_type -> SetAnimationRequest
	2, // 4: XmasPI.ChangeMode:output_type -> ModeChangeResponse
	4, // 5: XmasPI.SetLed:output_type -> SetLedResponse
	6, // 6: XmasPI.SetAnimation:output_type -> SetAnimationResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xmaspi_proto_init() }
func file_xmaspi_proto_init() {
	if File_xmaspi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xmaspi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModeChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xmaspi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModeChangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xmaspi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xmaspi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xmaspi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAnimationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xmaspi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAnimationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xmaspi_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xmaspi_proto_goTypes,
		DependencyIndexes: file_xmaspi_proto_depIdxs,
		EnumInfos:         file_xmaspi_proto_enumTypes,
		MessageInfos:      file_xmaspi_proto_msgTypes,
	}.Build()
	File_xmaspi_proto = out.File
	file_xmaspi_proto_rawDesc = nil
	file_xmaspi_proto_goTypes = nil
	file_xmaspi_proto_depIdxs = nil
}
